/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1440px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        serif: ["var(--font-serif)", "Playfair Display", "Charter", "Bitstream Charter", "Georgia", "Cambria", "Times New Roman", "serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "SFMono-Regular", "Menlo", "Consolas", "Courier New", "monospace"],
      },
      colors: {
        canvas: {
          DEFAULT: "#f3ebdd",
          deep: "#e8decc",
        },
        surface: {
          DEFAULT: "#f8f2e7",
          raised: "#ffffff",
          dark: "#0b2f25",
          "dark-raised": "#123f32",
        },
        forest: {
          50: "#f0f7f4",
          100: "#dbeef4",
          200: "#b9dfd5",
          300: "#85c5b3",
          400: "#54aa91",
          500: "#358d73",
          600: "#29745e",
          700: "#1e5947",
          800: "#123f32",
          900: "#0b2f25",
          950: "#071e18",
        },
        moss: {
          50: "#f6f8f1",
          100: "#ebf0df",
          200: "#d7e1bf",
          300: "#bccda3",
          400: "#9eb37f",
          500: "#7b885b",
          600: "#65734a",
          700: "#4f5b3a",
          800: "#3d472d",
          900: "#2d3521",
        },
        brass: {
          50: "#fbf5eb",
          100: "#f4e4c9",
          200: "#e6c89e",
          300: "#d8b17b",
          400: "#c99b5d",
          500: "#bd8b4a",
          600: "#a9793d",
          700: "#805927",
          800: "#65441c",
          900: "#483114",
          950: "#281b0a",
        },
        saffron: {
          50: "#fdf6e7",
          100: "#faedce",
          200: "#f5d79b",
          300: "#ebbe6e",
          400: "#e1aa50",
          500: "#d39736",
          600: "#ba7c24",
          700: "#965f1a",
          800: "#784917",
          900: "#5f3915",
          950: "#382109",
        },
        ink: {
          DEFAULT: "#16221e",
          soft: "#2e3d36",
          muted: "#4b5750",
          inverse: "#ffffff",
        },
        line: {
          DEFAULT: "rgba(35, 56, 43, 0.22)",
          strong: "rgba(35, 56, 43, 0.38)",
          dark: "rgba(243, 235, 221, 0.25)",
        },
        parchment: {
          50: "#fffaf1",
          100: "#f8f2e7",
          200: "#f3ebdd",
          300: "#e8decc",
          400: "#d9ccb4",
          500: "#c7b79c",
          600: "#b29f82",
          700: "#958165",
          800: "#76644d",
          900: "#594a37",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgba(31, 48, 37, 0.05)",
        card: "0 2px 10px rgba(31, 48, 37, 0.07), 0 1px 3px rgba(31, 48, 37, 0.04)",
        floating: "0 4px 18px rgba(11, 47, 37, 0.12), 0 1px 4px rgba(11, 47, 37, 0.05)",
        parchment: "0 2px 8px rgba(31, 48, 37, 0.05)",
        "brass-glow": "none",
        "forest-glow": "none",
        luxury: "0 4px 14px rgba(11, 47, 37, 0.08)",
      },
      borderRadius: {
        sm: "0.45rem",
        md: "0.8rem",
        lg: "1.2rem",
        xl: "1.7rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        civicRise: {
          from: { opacity: "0", transform: "translateY(6px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        civicPulse: {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.8", transform: "scale(1.02)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "civic-rise": "civicRise 0.4s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "civic-pulse": "civicPulse 2.5s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
