"""Automated Legal Dossier & IPO/NBA Form PDF Generator."""

import os
import uuid
from typing import List, Dict, Any
from app.schemas.dossier import DossierGenerationRequest, DossierGenerationResponse
from app.core.config import settings


class PDFDossierService:
    """Generates official pre-filled patent draft specifications and regulatory filing dossiers."""

    @classmethod
    def generate_dossier_pdf(
        cls, request: DossierGenerationRequest
    ) -> DossierGenerationResponse:
        """
        Creates structured PDF dossier and returns download metadata.
        """
        dossier_uuid = str(uuid.uuid4())[:8]
        os.makedirs(settings.STORAGE_DOSSIERS_DIR, exist_ok=True)
        filename = f"IP_SAKTI_Dossier_{dossier_uuid}.pdf"
        file_path = os.path.join(settings.STORAGE_DOSSIERS_DIR, filename)

        # Generate claim draft preview
        claims = [
            f"1. A synergistic herbal composition for {request.therapeutic_indication.lower() if hasattr(request, 'therapeutic_indication') else 'therapeutic treatment'}, comprising a therapeutically effective combination of {', '.join(request.botanical_ingredients)} in a predetermined synergistic weight ratio.",
            f"2. The herbal composition as claimed in claim 1, wherein the combination exhibits a Chou-Talalay Combination Index (CI) of less than 0.85.",
            f"3. A standardized extraction process for preparing the synergistic herbal composition of claim 1, comprising extraction at predetermined critical temperature and pressure parameters.",
            f"4. The herbal composition as claimed in claim 1, wherein the biological materials are sourced from verified cultivated habitats in {request.biological_source_origin}.",
        ]

        abstract = (
            f"The present invention relates to a novel synergistic herbal formulation comprising {', '.join(request.botanical_ingredients)} "
            f"exhibiting super-additive bioactivity with a combination index of {request.combination_index_ci or 0.68}. "
            f"The disclosure provides standardized extraction methods that overcome Indian Patents Act Section 3(e) admixture barriers."
        )

        source_dec = (
            f"Mandatory Section 10(4)(d)(ii) Disclosure: The biological resources utilized in the present application are "
            f"sourced from {request.biological_source_origin}, certified as cultivated flora under BDA 2024 compliance."
        )

        included_forms = []
        if request.include_ipo_form1:
            included_forms.append("IPO Form 1 (Application for Grant of Patent)")
        if request.include_ipo_form2_specification:
            included_forms.append("IPO Form 2 (Complete Specification Draft & Claims)")
        if request.include_nba_form_iii:
            included_forms.append("NBA Form III (Application for IPR on Biological Resources)")

        # Create mock file if reportlab is generating
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.pdfgen import canvas
            
            c = canvas.Canvas(file_path, pagesize=letter)
            c.setFont("Helvetica-Bold", 16)
            c.drawString(50, 750, "GOVERNMENT OF INDIA - PATENT OFFICE DRAFT DOSSIER")
            c.setFont("Helvetica", 10)
            c.drawString(50, 730, f"Generated by IP-SAKTI Sahayak (SIH26045) | Reference ID: {dossier_uuid}")
            c.line(50, 720, 560, 720)
            
            c.setFont("Helvetica-Bold", 12)
            c.drawString(50, 690, "FORM 2 - THE PATENTS ACT, 1970 - COMPLETE SPECIFICATION")
            c.setFont("Helvetica", 10)
            c.drawString(50, 670, f"Title of Invention: {request.formulation_title}")
            c.drawString(50, 650, f"Applicant: {request.applicant_name} ({request.applicant_address})")
            c.drawString(50, 630, f"Inventors: {', '.join(request.inventor_names)}")
            
            c.setFont("Helvetica-Bold", 11)
            c.drawString(50, 590, "ABSTRACT:")
            c.setFont("Helvetica", 9)
            c.drawString(50, 570, abstract[:100] + "...")
            
            c.setFont("Helvetica-Bold", 11)
            c.drawString(50, 530, "MANDATORY BIOLOGICAL SOURCE DECLARATION (Sec 10(4)(d)(ii)):")
            c.setFont("Helvetica", 9)
            c.drawString(50, 510, source_dec[:100] + "...")
            
            c.setFont("Helvetica-Bold", 11)
            c.drawString(50, 470, "DRAFT CLAIMS:")
            c.setFont("Helvetica", 9)
            y = 450
            for claim in claims:
                c.drawString(60, y, claim[:90] + "...")
                y -= 25

            c.save()
            file_size = os.path.getsize(file_path)
        except Exception:
            # Fallback text representation
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(f"IP-SAKTI Dossier\nTitle: {request.formulation_title}\n{abstract}\n{source_dec}")
            file_size = os.path.getsize(file_path)

        return DossierGenerationResponse(
            dossier_id=dossier_uuid,
            formulation_title=request.formulation_title,
            generated_pdf_url=f"/api/v1/dossier/download/{dossier_uuid}",
            file_size_bytes=file_size,
            included_forms=included_forms,
            draft_claims_preview=claims,
            abstract_preview=abstract,
            biological_source_declaration=source_dec,
        )
